// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBzzHn6iPbQmY7uB37f8_Gxsv6Pad-YE',
    appId: '1:409172478469:web:4d9d540f3a6c756da32a6c',
    messagingSenderId: '409172478469',
    projectId: 'testing-67819',
    authDomain: 'testing-67819.firebaseapp.com',
    storageBucket: 'testing-67819.appspot.com',
    measurementId: 'G-QL109G15VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwU1YF9U6fRio8p8tE0kmFyEBCbiN9-Ks',
    appId: '1:409172478469:android:a4e7a83188d2f5e6a32a6c',
    messagingSenderId: '409172478469',
    projectId: 'testing-67819',
    storageBucket: 'testing-67819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJtCJx4wekNYgJGlX9asOPpyOnzZrE_q8',
    appId: '1:409172478469:ios:845f77fea6e0457ea32a6c',
    messagingSenderId: '409172478469',
    projectId: 'testing-67819',
    storageBucket: 'testing-67819.appspot.com',
    iosClientId: '409172478469-0h8nvul3etheda0021nmotthg12j5hnp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tumbal',
  );
}
